name: Build Binaries

on:
  push:
    branch:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: grafana/loki-build-image:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.7'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y gcc-mingw-w64 p7zip-full
        npm install --global yarn@1.22.11

    - name: Build
      run: |
        echo -- -----------------
        env | sort
        echo -- -----------------
        go env | sort
        echo -- -----------------
        yarn --version
        echo -- -----------------
        git submodule update --init --recursive
        cd grafana \
          && go run build.go -goos windows -goarch amd64 -cc x86_64-w64-mingw32-gcc build \
          && make deps-js \
          && make build-js \
          && rm -rf node_modules/ packages/*/node_modules/ plugins-bundled/internal/input-datasource/node_modules/ \
          && 7za a ../grafana-homepath.zip -tzip conf plugins-bundled public scripts tools \
          && cd ..
        cp grafana/bin/windows-amd64/grafana-server.exe .
        cd tempo && make GOOS=windows GOARCH=amd64 tempo && cd ..
        cp tempo/bin/windows/tempo-amd64 ./tempo.exe
        git submodule foreach git log -n1 --oneline | tee revisions.txt

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        path: |
          *.exe
          *.txt
          *.zip
        if-no-files-found: error

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          *.exe
          *.txt
          *.zip
